---
title: "Assignment 3 Task 3 Michelle Geldin"
author: "Michelle Geldin"
date: "10/27/2021"
output:  
  html_document: 
    theme: yeti
    toc: yes
    code_folding: hide
---
## Overview

### Data Citation

## Setup

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, message = FALSE, warning = FALSE)
library(tidyverse)
library(here)
library(janitor)
library(kableExtra)
library(lubridate)
```

## Read in the data

```{r}
urchins_data <- read_csv(here("data", "urchins.csv" ))
```

## Section 1

### Data Wrangling

```{r}
urchins_data_clean <- urchins_data %>%
  clean_names()
```

### Data Visualization

```{r}
ggplot(data = urchins_data_clean, aes(x = size, fill = common_name)) +
  geom_histogram(bins = 10) +
  scale_fill_manual(values = c("purple", "red")) +
  labs(x = "Urchin Diameter (cm)",
       y = "Count of Urchins",
       title = "Comparison of Urchin diameter (cm) between Purple and Red Urchins") +
  facet_wrap(~ common_name) #How do I change the common name title?
```

Figure caption:


### Descriptive Statistics Table

Table Caption:

```{r}
urchins_stats <- urchins_data_clean %>%
  group_by(common_name) %>%
  summarize(mean_size = round(mean(size), 2),
            sd_size = round(sd(size), 2),
            median_size = round(median(size), 2),
            sample_size = n())

urchins_stats %>%
  kable(col.names = c("Common Name",
                      "Mean Diameter (cm)",
                      "Standard Deviation",
                      "Median Diameter (cm)", 
                      "Sample Size (n)")) %>%
  kable_styling(full_width = FALSE)

urchins_stats
```

### Description of Takeaways


## Section 2

### Data Wrangling

```{r}
purple_urchins <- urchins_data_clean %>%
  filter(common_name == "Purple Urchin") %>%
  mutate(date = mdy(date)) %>%
  mutate(year = year(date)) %>%
  mutate(site_full = case_when(
    site %in% c("NAPL") ~ "Naples Reef",
    site %in% c("AQUE") ~ "Arroyo Quemado Reef",
    site %in% c("CARP") ~ "Carpinteria Reef",
    site %in% c("MOHK") ~ "Mohawk Reef",
    site %in% c("IVEE") ~ "Isla Vista Reef"
  ))


purple_urchins

```

## Data Visualization

```{r, include = FALSE}
purple_urchins_obs <- purple_urchins %>%
  select(site, year)

purple_urchins_obs
  
```

```{r}
ggplot(data = purple_urchins_obs, aes(x = ))
```

