---
title: "Assignment 3 Task 4 Michelle Geldin"
author: "Michelle Geldin"
date: "10/29/2021"
output:
  html_document: 
    theme: yeti
    toc: yes
---
## Overview

### Data Citation

## Setup
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, message = FALSE, warning = FALSE)
library(tidyverse)
library(here)
library(janitor)
library(lubridate)
```

## Read in the data

```{r}
urchins_data <- read_csv(here("data", "urchins.csv"))
```

## Data Wrangling

```{r}
urchins_data_cleaner <- urchins_data %>%
  clean_names() %>%
  filter(site == "NAPL", common_name == "Purple Urchin") %>%
  mutate(date = mdy(date)) %>%
  mutate(year = year(date)) %>%
  filter(year == 2010)
  
```



```{r}
urchins_qq_plot <- ggplot(data = urchins_data_cleaner, aes(sample = size)) +
  geom_qq() +
  geom_qq_line() +
  facet_wrap(~ treatment) +
  labs(x = "Purple Urchin Size", y = "Purple Urchin Count", title = "Distribution of Purple Urchins at Naples Site in 2010 Sperated per Treatment")

urchins_qq_plot
```

Figure caption: add 1 - 2 sentences describing your main takeaways about the distribution of purple urchin sizes for each treatment (distribution, comparison, patterns, etc.). 

## Summary Table

Table caption:

```{r}
purple_urchins_stats <- urchins_data_cleaner %>%
  group_by(treatment) %>%
  summarize(mean_size = round(mean(size), 2),
            sd_size = round(sd(size), 2),
            sample_size = n())

purple_urchins_stats %>%
  kable(col.names = c("Treatment Type",
                      "Mean Diameter (cm)",
                      "Standard Deviation",
                      "Sample Size (n)")) %>%
  kable_styling(full_width = FALSE)
```

